//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSOAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HerculesSOAP.SecurityProvider2Soap")]
    public interface SecurityProvider2Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuarioPorNombreUsuario2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.ObtenerUsuarioPorNombreUsuario2Response> ObtenerUsuarioPorNombreUsuario2Async(HerculesSOAP.ObtenerUsuarioPorNombreUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarClaveUsuario2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.RecuperarClaveUsuario2Response> RecuperarClaveUsuario2Async(HerculesSOAP.RecuperarClaveUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiteMapRolPorNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.SiteMapRolPorNombreResponse> SiteMapRolPorNombreAsync(HerculesSOAP.SiteMapRolPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuario2EntidadRol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.BuscarUsuario2EntidadRolResponse> BuscarUsuario2EntidadRolAsync(HerculesSOAP.BuscarUsuario2EntidadRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarEntidadesAsociadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.BuscarEntidadesAsociadasResponse> BuscarEntidadesAsociadasAsync(HerculesSOAP.BuscarEntidadesAsociadasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.ValidarUsuario2Response> ValidarUsuario2Async(HerculesSOAP.ValidarUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.ActualizarUsuario2Response> ActualizarUsuario2Async(HerculesSOAP.ActualizarUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambioClaveUsuario2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.CambioClaveUsuario2Response> CambioClaveUsuario2Async(HerculesSOAP.CambioClaveUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarNitTokenEntidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.ValidarNitTokenEntidadResponse> ValidarNitTokenEntidadAsync(HerculesSOAP.ValidarNitTokenEntidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosUsuarioSSO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.ObtenerDatosUsuarioSSOResponse> ObtenerDatosUsuarioSSOAsync(HerculesSOAP.ObtenerDatosUsuarioSSORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarEntidadxCodigo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HerculesSOAP.BuscarEntidadxCodigoResponse> BuscarEntidadxCodigoAsync(HerculesSOAP.BuscarEntidadxCodigoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class customMembershipUser2
    {
        
        private string loginField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string primerNombreField;
        
        private string segundoNombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string registroProfesionalField;
        
        private string profesionField;
        
        private string emailField;
        
        private bool requiereCambioClaveField;
        
        private int erroresLoginField;
        
        private System.DateTime fechaCreacionField;
        
        private System.DateTime fechaUltActualizacionField;
        
        private bool bloqueadoField;
        
        private bool deshabilitadoField;
        
        private string tipoUsuarioField;
        
        private string programaUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PrimerNombre
        {
            get
            {
                return this.primerNombreField;
            }
            set
            {
                this.primerNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SegundoNombre
        {
            get
            {
                return this.segundoNombreField;
            }
            set
            {
                this.segundoNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PrimerApellido
        {
            get
            {
                return this.primerApellidoField;
            }
            set
            {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SegundoApellido
        {
            get
            {
                return this.segundoApellidoField;
            }
            set
            {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RegistroProfesional
        {
            get
            {
                return this.registroProfesionalField;
            }
            set
            {
                this.registroProfesionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Profesion
        {
            get
            {
                return this.profesionField;
            }
            set
            {
                this.profesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool RequiereCambioClave
        {
            get
            {
                return this.requiereCambioClaveField;
            }
            set
            {
                this.requiereCambioClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int ErroresLogin
        {
            get
            {
                return this.erroresLoginField;
            }
            set
            {
                this.erroresLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime FechaCreacion
        {
            get
            {
                return this.fechaCreacionField;
            }
            set
            {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime FechaUltActualizacion
        {
            get
            {
                return this.fechaUltActualizacionField;
            }
            set
            {
                this.fechaUltActualizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Bloqueado
        {
            get
            {
                return this.bloqueadoField;
            }
            set
            {
                this.bloqueadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool Deshabilitado
        {
            get
            {
                return this.deshabilitadoField;
            }
            set
            {
                this.deshabilitadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TipoUsuario
        {
            get
            {
                return this.tipoUsuarioField;
            }
            set
            {
                this.tipoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ProgramaUsuario
        {
            get
            {
                return this.programaUsuarioField;
            }
            set
            {
                this.programaUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuarioPorNombreUsuario2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerUsuarioPorNombreUsuario2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        public ObtenerUsuarioPorNombreUsuario2Request()
        {
        }
        
        public ObtenerUsuarioPorNombreUsuario2Request(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuarioPorNombreUsuario2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerUsuarioPorNombreUsuario2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HerculesSOAP.customMembershipUser2 ObtenerUsuarioPorNombreUsuario2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public ObtenerUsuarioPorNombreUsuario2Response()
        {
        }
        
        public ObtenerUsuarioPorNombreUsuario2Response(HerculesSOAP.customMembershipUser2 ObtenerUsuarioPorNombreUsuario2Result, string mensaje)
        {
            this.ObtenerUsuarioPorNombreUsuario2Result = ObtenerUsuarioPorNombreUsuario2Result;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarClaveUsuario2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarClaveUsuario2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string aplicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ipOrigen;
        
        public RecuperarClaveUsuario2Request()
        {
        }
        
        public RecuperarClaveUsuario2Request(string aplicacion, string usuario, string identificacion, string email, string ipOrigen)
        {
            this.aplicacion = aplicacion;
            this.usuario = usuario;
            this.identificacion = identificacion;
            this.email = email;
            this.ipOrigen = ipOrigen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarClaveUsuario2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarClaveUsuario2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RecuperarClaveUsuario2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public RecuperarClaveUsuario2Response()
        {
        }
        
        public RecuperarClaveUsuario2Response(bool RecuperarClaveUsuario2Result, string mensaje)
        {
            this.RecuperarClaveUsuario2Result = RecuperarClaveUsuario2Result;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SiteMapRolPorNombre", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SiteMapRolPorNombreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Aplicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Rol;
        
        public SiteMapRolPorNombreRequest()
        {
        }
        
        public SiteMapRolPorNombreRequest(string Aplicacion, string Rol)
        {
            this.Aplicacion = Aplicacion;
            this.Rol = Rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SiteMapRolPorNombreResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SiteMapRolPorNombreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HerculesSOAP.ArrayOfXElement SiteMapRolPorNombreResult;
        
        public SiteMapRolPorNombreResponse()
        {
        }
        
        public SiteMapRolPorNombreResponse(HerculesSOAP.ArrayOfXElement SiteMapRolPorNombreResult)
        {
            this.SiteMapRolPorNombreResult = SiteMapRolPorNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarUsuario2EntidadRol", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarUsuario2EntidadRolRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Aplicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CodEntidad;
        
        public BuscarUsuario2EntidadRolRequest()
        {
        }
        
        public BuscarUsuario2EntidadRolRequest(string Aplicacion, string Usuario, string CodEntidad)
        {
            this.Aplicacion = Aplicacion;
            this.Usuario = Usuario;
            this.CodEntidad = CodEntidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarUsuario2EntidadRolResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarUsuario2EntidadRolResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HerculesSOAP.ArrayOfXElement BuscarUsuario2EntidadRolResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public BuscarUsuario2EntidadRolResponse()
        {
        }
        
        public BuscarUsuario2EntidadRolResponse(HerculesSOAP.ArrayOfXElement BuscarUsuario2EntidadRolResult, string mensaje)
        {
            this.BuscarUsuario2EntidadRolResult = BuscarUsuario2EntidadRolResult;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarEntidadesAsociadas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarEntidadesAsociadasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CodigoEntidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CodigoEntidadAsociada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int Operacion;
        
        public BuscarEntidadesAsociadasRequest()
        {
        }
        
        public BuscarEntidadesAsociadasRequest(string CodigoEntidad, string CodigoEntidadAsociada, int Operacion)
        {
            this.CodigoEntidad = CodigoEntidad;
            this.CodigoEntidadAsociada = CodigoEntidadAsociada;
            this.Operacion = Operacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarEntidadesAsociadasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarEntidadesAsociadasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HerculesSOAP.ArrayOfXElement BuscarEntidadesAsociadasResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public BuscarEntidadesAsociadasResponse()
        {
        }
        
        public BuscarEntidadesAsociadasResponse(HerculesSOAP.ArrayOfXElement BuscarEntidadesAsociadasResult, string mensaje)
        {
            this.BuscarEntidadesAsociadasResult = BuscarEntidadesAsociadasResult;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarUsuario2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarUsuario2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string applicationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ip;
        
        public ValidarUsuario2Request()
        {
        }
        
        public ValidarUsuario2Request(string applicationName, string Login, string password, string ip)
        {
            this.applicationName = applicationName;
            this.Login = Login;
            this.password = password;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarUsuario2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarUsuario2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ValidarUsuario2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public ValidarUsuario2Response()
        {
        }
        
        public ValidarUsuario2Response(bool ValidarUsuario2Result, string mensaje)
        {
            this.ValidarUsuario2Result = ValidarUsuario2Result;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarUsuario2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarUsuario2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IdTipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string NumeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string PrimerNombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SegundoNombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string PrimerApellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string SegundoApellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string RegistroProfesional;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string Profesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string LoginUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string ip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string aplicacion;
        
        public ActualizarUsuario2Request()
        {
        }
        
        public ActualizarUsuario2Request(string Login, int IdTipoDocumento, string NumeroDocumento, string PrimerNombre, string SegundoNombre, string PrimerApellido, string SegundoApellido, string email, string RegistroProfesional, string Profesion, string LoginUser, string ip, string aplicacion)
        {
            this.Login = Login;
            this.IdTipoDocumento = IdTipoDocumento;
            this.NumeroDocumento = NumeroDocumento;
            this.PrimerNombre = PrimerNombre;
            this.SegundoNombre = SegundoNombre;
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
            this.email = email;
            this.RegistroProfesional = RegistroProfesional;
            this.Profesion = Profesion;
            this.LoginUser = LoginUser;
            this.ip = ip;
            this.aplicacion = aplicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarUsuario2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActualizarUsuario2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ActualizarUsuario2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public ActualizarUsuario2Response()
        {
        }
        
        public ActualizarUsuario2Response(bool ActualizarUsuario2Result, string mensaje)
        {
            this.ActualizarUsuario2Result = ActualizarUsuario2Result;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambioClaveUsuario2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CambioClaveUsuario2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string applicationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string oldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string newPassword;
        
        public CambioClaveUsuario2Request()
        {
        }
        
        public CambioClaveUsuario2Request(System.Nullable<int> tipo, string applicationName, string login, string oldPassword, string newPassword)
        {
            this.tipo = tipo;
            this.applicationName = applicationName;
            this.login = login;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambioClaveUsuario2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CambioClaveUsuario2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CambioClaveUsuario2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public CambioClaveUsuario2Response()
        {
        }
        
        public CambioClaveUsuario2Response(bool CambioClaveUsuario2Result, string mensaje)
        {
            this.CambioClaveUsuario2Result = CambioClaveUsuario2Result;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarNitTokenEntidad", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarNitTokenEntidadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string tipoEntidad;
        
        public ValidarNitTokenEntidadRequest()
        {
        }
        
        public ValidarNitTokenEntidadRequest(string nit, string token, string tipoEntidad)
        {
            this.nit = nit;
            this.token = token;
            this.tipoEntidad = tipoEntidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarNitTokenEntidadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarNitTokenEntidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ValidarNitTokenEntidadResult;
        
        public ValidarNitTokenEntidadResponse()
        {
        }
        
        public ValidarNitTokenEntidadResponse(int ValidarNitTokenEntidadResult)
        {
            this.ValidarNitTokenEntidadResult = ValidarNitTokenEntidadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDatosUsuarioSSO", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerDatosUsuarioSSORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login;
        
        public ObtenerDatosUsuarioSSORequest()
        {
        }
        
        public ObtenerDatosUsuarioSSORequest(string login)
        {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDatosUsuarioSSOResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerDatosUsuarioSSOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HerculesSOAP.ArrayOfXElement ObtenerDatosUsuarioSSOResult;
        
        public ObtenerDatosUsuarioSSOResponse()
        {
        }
        
        public ObtenerDatosUsuarioSSOResponse(HerculesSOAP.ArrayOfXElement ObtenerDatosUsuarioSSOResult)
        {
            this.ObtenerDatosUsuarioSSOResult = ObtenerDatosUsuarioSSOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarEntidadxCodigo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarEntidadxCodigoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string codigoentidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Aplicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tipoentidad;
        
        public BuscarEntidadxCodigoRequest()
        {
        }
        
        public BuscarEntidadxCodigoRequest(string codigoentidad, System.Nullable<int> Aplicacion, System.Nullable<int> tipoentidad)
        {
            this.codigoentidad = codigoentidad;
            this.Aplicacion = Aplicacion;
            this.tipoentidad = tipoentidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarEntidadxCodigoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarEntidadxCodigoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HerculesSOAP.ArrayOfXElement BuscarEntidadxCodigoResult;
        
        public BuscarEntidadxCodigoResponse()
        {
        }
        
        public BuscarEntidadxCodigoResponse(HerculesSOAP.ArrayOfXElement BuscarEntidadxCodigoResult)
        {
            this.BuscarEntidadxCodigoResult = BuscarEntidadxCodigoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SecurityProvider2SoapChannel : HerculesSOAP.SecurityProvider2Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SecurityProvider2SoapClient : System.ServiceModel.ClientBase<HerculesSOAP.SecurityProvider2Soap>, HerculesSOAP.SecurityProvider2Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SecurityProvider2SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SecurityProvider2SoapClient.GetBindingForEndpoint(endpointConfiguration), SecurityProvider2SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityProvider2SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SecurityProvider2SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityProvider2SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SecurityProvider2SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityProvider2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.ObtenerUsuarioPorNombreUsuario2Response> ObtenerUsuarioPorNombreUsuario2Async(HerculesSOAP.ObtenerUsuarioPorNombreUsuario2Request request)
        {
            return base.Channel.ObtenerUsuarioPorNombreUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.RecuperarClaveUsuario2Response> RecuperarClaveUsuario2Async(HerculesSOAP.RecuperarClaveUsuario2Request request)
        {
            return base.Channel.RecuperarClaveUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.SiteMapRolPorNombreResponse> SiteMapRolPorNombreAsync(HerculesSOAP.SiteMapRolPorNombreRequest request)
        {
            return base.Channel.SiteMapRolPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.BuscarUsuario2EntidadRolResponse> BuscarUsuario2EntidadRolAsync(HerculesSOAP.BuscarUsuario2EntidadRolRequest request)
        {
            return base.Channel.BuscarUsuario2EntidadRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.BuscarEntidadesAsociadasResponse> BuscarEntidadesAsociadasAsync(HerculesSOAP.BuscarEntidadesAsociadasRequest request)
        {
            return base.Channel.BuscarEntidadesAsociadasAsync(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.ValidarUsuario2Response> ValidarUsuario2Async(HerculesSOAP.ValidarUsuario2Request request)
        {
            return base.Channel.ValidarUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.ActualizarUsuario2Response> ActualizarUsuario2Async(HerculesSOAP.ActualizarUsuario2Request request)
        {
            return base.Channel.ActualizarUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.CambioClaveUsuario2Response> CambioClaveUsuario2Async(HerculesSOAP.CambioClaveUsuario2Request request)
        {
            return base.Channel.CambioClaveUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.ValidarNitTokenEntidadResponse> ValidarNitTokenEntidadAsync(HerculesSOAP.ValidarNitTokenEntidadRequest request)
        {
            return base.Channel.ValidarNitTokenEntidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.ObtenerDatosUsuarioSSOResponse> ObtenerDatosUsuarioSSOAsync(HerculesSOAP.ObtenerDatosUsuarioSSORequest request)
        {
            return base.Channel.ObtenerDatosUsuarioSSOAsync(request);
        }
        
        public System.Threading.Tasks.Task<HerculesSOAP.BuscarEntidadxCodigoResponse> BuscarEntidadxCodigoAsync(HerculesSOAP.BuscarEntidadxCodigoRequest request)
        {
            return base.Channel.BuscarEntidadxCodigoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecurityProvider2Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SecurityProvider2Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecurityProvider2Soap))
            {
                //return new System.ServiceModel.EndpointAddress("http://192.168.47.134/wsSecurityProvider2/MembershipProvider2.asmx");
                return new System.ServiceModel.EndpointAddress("http://192.168.37.131/wsSecurityProvider2/MembershipProvider2.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SecurityProvider2Soap12))
            {
                //return new System.ServiceModel.EndpointAddress("http://192.168.47.134/wsSecurityProvider2/MembershipProvider2.asmx");
                return new System.ServiceModel.EndpointAddress("http://192.168.37.131/wsSecurityProvider2/MembershipProvider2.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SecurityProvider2Soap,
            
            SecurityProvider2Soap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
